### ISSUE TITLE
SystemExit: 'jaydebeapi' Python package is missing

### ISSUE THREAD

**Issue by catodiaz** [UMEP-dev/UMEP-processing#78] opened 2024-05-01 20:41 UTC
I have the following problem after installing UMEP for processing. 

![image](https://github.com/UMEP-dev/UMEP-processing/assets/168681975/0558cc95-c3a2-447e-af4c-1faf49ca83c7)

**Comment by catodiaz** [comment] 2024-05-01 20:46
Also there is a problem installing UMEP plugin:

2024-05-01T14:43:58     WARNING    Error running (1, ['C:\\OSGeo4W\\apps\\Python312\\..\\..\\bin\\pythonw.exe', '-m', 'pip', 'install', 'umep-reqs', '-U', '--user', '--prefer-binary']):
             Collecting umep-reqs
              Using cached umep_reqs-2.1.1-py3-none-any.whl.metadata (301 bytes)
             INFO: pip is looking at multiple versions of umep-reqs to determine which version is compatible with other requirements. This could take a while.
              Using cached umep_reqs-2.1-py3-none-any.whl.metadata (310 bytes)
              Using cached umep_reqs-2.0.1-py3-none-any.whl.metadata (307 bytes)
             Collecting supy==2022.9.22 (from umep-reqs)
              Using cached supy-2022.9.22-py3-none-any.whl.metadata (4.7 kB)
             Collecting numba==0.56.4 (from umep-reqs)
              Using cached numba-0.56.4.tar.gz (2.4 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'error'
              error: subprocess-exited-with-error
              
              × Getting requirements to build wheel did not run successfully.
              │ exit code: 1
              ╰─> [23 lines of output]
              C:\Users\catod\AppData\Local\Temp\pip-install-svoigijk\numba_352f43d178324713a7775461168eaa6a\versioneer.py:335: SyntaxWarning: invalid escape sequence '\s'
              LONG_VERSION_PY['git'] = '''
              Traceback (most recent call last):
              File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in 
              main()
              File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
              return hook(config_settings)
              ^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\catod\AppData\Local\Temp\pip-build-env-b1oilom5\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=['wheel'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\catod\AppData\Local\Temp\pip-build-env-b1oilom5\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
              self.run_setup()
              File "C:\Users\catod\AppData\Local\Temp\pip-build-env-b1oilom5\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
              super().run_setup(setup_script=setup_script)
              File "C:\Users\catod\AppData\Local\Temp\pip-build-env-b1oilom5\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
              exec(code, locals())
              File "", line 51, in 
              File "", line 48, in _guard_py_ver
              RuntimeError: Cannot install on Python version 3.12.3; only versions >=3.7,              [end of output]
              
              note: This error originates from a subprocess, and is likely not a problem with pip.
             error: subprocess-exited-with-error
             
             × Getting requirements to build wheel did not run successfully.
             │ exit code: 1
             ╰─> See above for output.
             
             note: This error originates from a subprocess, and is likely not a problem with pip.
             
2024-05-01T14:43:58     WARNING    Traceback (most recent call last):
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\__init__.py", line 18, in 
              import supy as sp
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ModuleNotFoundError: No module named 'supy'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\umep_installer.py", line 129, in setup_umep_python
              import supy as sp
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ModuleNotFoundError: No module named 'supy'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\__init__.py", line 38, in 
              setup_umep_python(ver=None)
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\umep_installer.py", line 136, in setup_umep_python
              install_umep_python(ver)
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\util\umep_installer.py", line 90, in install_umep_python
              str_info = subprocess.check_output(
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\subprocess.py", line 466, in check_output
              return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\subprocess.py", line 571, in run
              raise CalledProcessError(retcode, process.args,
             subprocess.CalledProcessError: Command '['C:\\OSGeo4W\\apps\\Python312\\..\\..\\bin\\pythonw.exe', '-m', 'pip', 'install', 'umep-reqs', '-U', '--user', '--prefer-binary']' returned non-zero exit status 1.
             
2024-05-01T14:44:12     WARNING    Exception
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\__init__.py", line 36, in 
              setup_supy(ver=None)
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\supy_installer.py", line 134, in setup_supy
              install_supy(ver)
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\supy_installer.py", line 103, in install_supy
              raise RuntimeError(f"UMEP couldn't install supy{str_ver}!") from Exception
             RuntimeError: UMEP couldn't install supy!
             
2024-05-01T14:44:15     INFO    Application state:
             QGIS_PREFIX_PATH env var: C:/OSGeo4W/apps/qgis-ltr
             Prefix: C:/OSGeo4W/apps/qgis-ltr
             Plugin Path: C:/OSGeo4W/apps/qgis-ltr/plugins
             Package Data Path: C:/OSGeo4W/apps/qgis-ltr/.
             Active Theme Name: default
             Active Theme Path: C:/OSGeo4W/apps/qgis-ltr/./resources/themes\default\icons/
             Default Theme Path: :/images/themes/default/
             SVG Search Paths: C:/OSGeo4W/apps/qgis-ltr/./svg/
              C:/Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
             User DB Path: C:/OSGeo4W/apps/qgis-ltr/./resources/qgis.db
             Auth DB Path: C:/Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db

**Comment by j3r3m1** [comment] 2024-05-02 08:30
Not sure I understand your 2 messages. The second is the one you got when installing and the first when you tried launching the plugin ?

Because in the second it seems supy has not been installed successfully while in the first it is jaydebeapi that has not been installed successfully. 

For the supy related issue, maybe @sunt05 can help.

Concerning jaydebeapi, can you try in the QGIS Python console to enter the following:
```python
import pip
pip.main(['install', 'jaydebeapi'])

**Comment by sunt05** [comment] 2024-05-02 08:52
The exception mentioning "supy" appears to stem from an upstream issue, not "supy" itself—I noticed terms like "timeout," suggesting a network problem or a blockage caused by the initial error.

Unfortunately, I can't be much help here.

**Comment by catodiaz** [comment] 2024-05-02 21:53
Hi, thanks for you response.
Both problems are from when I try to install de plugins. I have not tried to launch the plugins because I have a lot of error messages. Every time I open QGIS I receive a message about installing missing python modules and than a message that UMEP could not install python packages. There are other messages such as "Plugin UMEP: This plugin is disabled because it previously crashed QGIS."

I tried the lines in the QGIS python console but I get more errors:

![image](https://github.com/UMEP-dev/UMEP-processing/assets/168681975/1a2a92a9-90c9-4521-a3c7-5634f79e5dba)

**Comment by j3r3m1** [comment] 2024-05-03 05:53
Try copying and pasting lines one by one, it should solve this problem.

**Comment by catodiaz** [comment] 2024-05-04 00:45
It worked line by line. Jaydebapi installed, a similar issue appeared with "numba". Did the same procedure and it worked. Then I restarted the computer. 

I opened QGIS again and still there is a problem: " Python error : Couldn't load plugin 'processing_umep' due to an error when calling its classFactory() method See message log (Python Error) for more details."

Python Error says:

2024-05-03T18:38:14     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\__init__.py", line 46, in classFactory
              from .processing_umep import ProcessingUMEPPlugin
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep.py", line 38, in 
              from .processing_umep_provider import ProcessingUMEPProvider
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\processing_umep_provider.py", line 61, in 
              from .postprocessor.urock_analyser_algorithm import URockAnalyserAlgorithm
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/catod/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\postprocessor\urock_analyser_algorithm.py", line 58, in 
              import xarray as xr
              File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ModuleNotFoundError: No module named 'xarray'

**Comment by j3r3m1** [comment] 2024-05-04 17:14
@catodiaz I do not know why but I have received an alert that you have posted a new message and can read it from my email box but not from GitHub. Can you repost it ?

**Comment by catodiaz** [comment] 2024-05-09 01:24
Hi j3r3m1, sorry that I did not reply before, previous days were busy.
I deleted the message you mention because I had two more issues but I applied the same process you suggested and I could install what was missing. 
It worked line by line, 4 days ago I could install Jaydebapi. A similar issue appeared with "numba". Did the same procedure and it worked. Then I restarted the computer. Later had another problem with "xarray", problem solved with the same procedure.

Before, at the top of the QGIS work area I had the message " Python error : Couldn't load plugin 'processing_umep' due to an error when calling its classFactory() method See message log (Python Error) for more details." But now its gone and I think the plugin is ok. However, every time I start QGIS these messages appear:
![Screenshot 2024-05-08 190829](https://github.com/UMEP-dev/UMEP-processing/assets/168681975/e884c454-5bec-4c7f-b7c7-9871c175242b)
![Screenshot 2024-05-08 190906](https://github.com/UMEP-dev/UMEP-processing/assets/168681975/347c17bf-b9e8-4c07-819a-5afcb3f1747b)

After that the program looks ok, no error messages, but I haven't have time to work with UMEP to check.

**Comment by j3r3m1** [comment] 2024-05-13 07:14
OK maybe this error comes from the supy dependency which is not solved right now. Except the SUEWS plugin, everything should be fine. Let us know if it is the case and if so please close the issue as we still have issue #79 describing the SUEWS / Python 3.12 compatibility issue.

**Comment by catodiaz** [comment] 2024-05-15 03:33
Understood. Thanks for all your help.

**Comment by catodiaz** [comment] 2024-05-15 03:35
issue closed

**Closed** 2024-05-15 03:34 UTC
